name: espot_power
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #iOS
  cupertino_icons: ^1.0.2

  #Notifier
  fluttertoast: ^8.1.2

  #Theme
  dynamic_color: ^1.5.4

  #Local cache
  shared_preferences: ^2.0.17

  #Network
  dio: ^5.1.2
  graphql_flutter: ^5.1.2

  #UI
  flutter_svg: ^2.0.5
  cached_network_image: ^3.2.3

  #Page transition
  page_transition: ^2.0.9

  #Routing
  #go_router: ^7.0.1

  #easy loading
  flutter_easyloading: ^3.0.5

  #Expandable
  expandable: ^5.0.1

  #Firebase
  firebase_core: ^2.12.0
  firebase_messaging: ^14.6.0
  firebase_auth: ^4.6.0

  #Multiple languages
  easy_localization: ^3.0.1

  #Notificaiton
  flutter_local_notifications: ^14.0.0+2

  #Dependency Injection
  get_it: ^7.2.0

  #State management
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  #Icons
  material_design_icons_flutter: ^6.0.7096

  #url_strategy
  url_strategy: ^0.2.0

  #pin_code_field
  pin_code_fields: ^8.0.1
  url_launcher: ^6.1.10
  rxdart: ^0.27.7
  path_provider: ^2.0.14
  flutter_isolate: ^2.0.4
  cloud_firestore: ^4.5.2
  firebase_storage: ^11.1.1
  image_picker: ^1.0.5
  carousel_slider: ^4.2.1

  #Snack
  another_flushbar: ^1.10.29

  #Phone
  country_code_picker: ^3.0.0
  adaptive_dialog: ^1.8.3
  star_menu: ^3.1.4

  flutter_cupertino_datetime_picker: ^3.0.0
  jwt_decoder: ^2.0.1
  dotted_border: 2.0.0+3
  flutter_dropzone: 3.0.6
  file_picker: ^5.0.0
  dropdown_button2: ^2.3.9
  crypto: ^3.0.3
  pattern_formatter: ^3.0.0
  webview_flutter: ^4.4.2
  html_unescape: ^2.0.0
  flutter_html: ^3.0.0-beta.2
  currency_text_input_formatter: ^2.1.10
  qr_code_scanner: ^1.0.1
  geolocator: ^10.1.0
  location: ^5.0.3
  scan: ^1.6.0
  loading_indicator: ^3.1.1
  google_maps_flutter: ^2.5.0
  permission_handler: ^11.0.1

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - env.json
    - assets/countries/
    - assets/images/
    - assets/localization/
    - assets/fonts/

  fonts:
    - family: SVN-GOTHAM
      fonts:
        - asset: assets/fonts/svn_gotham_thin.ttf
          weight: 100
        - asset: assets/fonts/svn_gotham_xlight.ttf
          weight: 200
        - asset: assets/fonts/svn_gotham_light.ttf
          weight: 300
        - asset: assets/fonts/svn_gotham_book.ttf
          weight: 400
        - asset: assets/fonts/svn_gotham_regular.ttf
          weight: 500
        - asset: assets/fonts/svn_gotham_bold.ttf
          weight: 600
        - asset: assets/fonts/svn_gotham_black.ttf
          weight: 700
        - asset: assets/fonts/svn_gotham_ultra.ttf
          weight: 800
